lostandfound/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('changepassword/', views.without_old_change_password, name='wochangepassword'),
]

lostandfound/lost/urls.py
from django.urls import path
from . import views
from .views import list_lost_items, submit_lost_item, match_found_items

urlpatterns = [
    path('submit-lost/', submit_lost_item, name='submit_lost'),
    path('', list_lost_items, name='list_lost'),
    path('list_confidence/', match_found_items, name='list_confidence'),
    path('list_confidence/<int:lost_id>/', views.match_found_items, name='list_confidence'),
    path('<int:id>/', views.lost_detail, name='lost_detail'),
    path('user-items/', views.user_lost_items, name='user_lost_items'),
    path('edit/<int:id>/', views.edit_lost_item, name='edit_lost_item'),
    path('delete/<int:id>/', views.delete_lost_item, name='delete_lost_item'),
]

lostandfound/lostandfound/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lost.urls')),
    path('found/', include('found.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    
]

lostandfound/templates/common_codes/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <title>
    {% block title %}
        
    {% endblock title %}
        </title>
</head>
<body>
    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg bg-body-tertiary border border-success-subtle">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="{% url 'list_lost' %}" style="font-weight: 700; color: darkgreen; font-size: 24px;">LOFO</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'list_lost' %}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'submit_lost' %}">Submit Lost Item</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'submit_found' %}">Submit Found Item</a>
                          </li>
                          <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'accounts:dashboard' %}">DashBoard</a>
                           
                            {% endif %}
                          </li>
                        </ul>
                        <!-- <form class="d-flex align-items-center" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                          <button class="btn btn-outline-success px-3 py-1" type="submit" style="white-space: nowrap;">
                            Search found item
                          </button>
                        </form> -->
                        {% if user.is_authenticated %}
                          <nav class="nav">
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:dashboard' %}">Welcome, {{ user.username }}  👋</a>
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
                          </nav>
                        
                        {% else %}

                          <nav class="nav">
                            <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
                          </nav>

                        {% endif %}
                                              
                      </div>
                    </div>
                  </nav>



            </div>
        </div>
         {% if messages %}
          <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1060;">
            {% for message in messages %}
              <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="5000" data-bs-autohide="true">
                <div class="toast-header bg-{{ message.tags }} text-white">
                  <!-- Optional icon/image -->
                  <svg class="rounded me-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                    {% if message.tags == "success" %}
                      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.854 10.854l4.5-4.5-.708-.708L6.5 9.293 4.854 7.646l-.708.708 2 2a.5.5 0 0 0 .708 0z"/>
                    {% elif message.tags == "danger" %}
                      <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zM5.293 4.707L8 7.414l2.707-2.707.707.707L8.707 8.121l2.707 2.707-.707.707L8 8.828l-2.707 2.707-.707-.707L7.293 8.121 4.586 5.414l.707-.707z"/>
                    {% else %}
                      <circle cx="8" cy="8" r="8"/>
                    {% endif %}
                  </svg>
                  <strong class="me-auto text-capitalize">{{ message.tags }}</strong>
                  <small>Just now</small>
                  <button type="button" class="btn-close btn-close-white ms-2" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                  {{ message }}
                </div>
              </div>
            {% endfor %}
          </div>
        {% endif %}



    </div>

    <div class="container">
      <div class="row">
        <div class="col-12">

         

          {% block content %}
        
          {% endblock content %}


        </div>
      </div>
    </div>
    
        
    






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function () {
      const toastElList = [].slice.call(document.querySelectorAll('.toast'))
      toastElList.forEach(function (toastEl) {
        new bootstrap.Toast(toastEl).show()
      })
    });
  </script>


  </body>
</html>